pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - base=master
      - "#approved-reviews-by>=0"
      #      - status-success=continuous-integration/travis-ci/pr
      #      - "#approved-reviews-by>=2"
    actions:
      merge:
        method: merge
  
